version: "3.8"
services:
  jupyter:
    container_name: jupyter
    build:
      context: ./jupyter
    ports:
      - 8888:8888
    volumes:
      - ${PWD}/jupyter/common:/home/jovyan/work/common
      - ${PWD}/rg_sound_generation/mapping_models/examples:/home/jovyan/work/rg_sound_generation
      - ${PWD}/rg_production/resources:/home/jovyan/work/rg_production
    environment:
      - JUPYTER_ENABLE_LAB=yes
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "1884:1883"
    volumes:
      - ${PWD}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
  webapps:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/example_path/public:/usr/share/nginx/html/example:ro
    network_mode: "host"
  evaluation:
    container_name: evaluation
    build:
      context: ./rg_evaluation
    ports:
      - 5000:5000
